import path from "path"
import { fileURLToPath } from "url"

import {
  parseCatalog,
  REFRESH_HINT,
  resolveReleaseChannel,
  staleness,
  STALE_FAIL_DAYS,
  STALE_WARN_DAYS,
} from "./models-catalog"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = (process.env.WANLAICODE_MODELS_URL ?? process.env.OPENCODE_MODELS_URL) || "https://models.dev"
const snapshotPath = path.join(dir, "src/provider/models-snapshot.js")
// 入库的兜底目录。models-snapshot.js 是构建产物且被 gitignore，Linux/mac 的 checkout 又是
// clean:true（git clean -ffdx 会删掉 ignored 文件），所以拿它当兜底在 CI 上永远不可能生效
// —— 只有 Windows 因 clean:false 侥幸留着残留。改用这份入库文件，fresh checkout 后必然存在。
const pinnedPath = path.join(dir, "src/provider/models-pinned.json")
const pinnedMetaPath = path.join(dir, "src/provider/models-pinned.meta.json")

// 取目录的整体超时。没有它，兜底只对 fast-fail 型网络故障（直连被 reset）有效：
// 防火墙丢 SYN 不回 RST、代理应答 CONNECT 后停滞、慢速滴流这几种 drop 型故障会让
// fetch 既不成功也不失败，而 Prepare/Build 都没有 timeout-minutes，发版从"秒级回落
// 兜底"退化成挂到 job 默认 360 分钟超时才红。
const NETWORK_TIMEOUT_MS = 30_000

const channel = resolveReleaseChannel(process.env)

// CI 上用 annotation 让告警浮到 Actions 运行页顶部，而不是淹没在几千行构建日志里；
// 本地跑保持普通输出，避免打出 ::warning:: 这种裸标记。
const warn = (msg: string) =>
  console.warn(process.env.GITHUB_ACTIONS ? `::warning::${msg}` : `[models] ${msg}`)

// 陈旧检查：把"目录悄悄过期"重新变成看得见的事。没有它，刷新一旦没人跑，
// 产品里内置的模型目录会无限期冻结而所有日志都是绿的。
async function checkStale(): Promise<void> {
  const metaFile = Bun.file(pinnedMetaPath)
  if (!(await metaFile.exists())) {
    warn(`缺少 ${path.basename(pinnedMetaPath)}，无法判断 pinned 目录的新鲜度`)
    return
  }
  // meta 自身语法坏掉（合并冲突残留、手工编辑）时按既有降级模式告警放行：文件缺失与
  // fetchedAt 非法两支都是 warn，唯独这里裸抛会让离线构建在所有 channel 上崩掉，
  // 与"90 天硬失败只拦 prod"的承诺相反。
  let meta: { fetchedAt?: unknown; providers?: unknown }
  try {
    meta = JSON.parse(await metaFile.text())
  } catch (e) {
    warn(`${path.basename(pinnedMetaPath)} 解析失败（${(e as Error).message}），无法判断 pinned 目录的新鲜度`)
    return
  }
  const result = staleness(meta.fetchedAt, Date.now())
  if (!result.known) {
    // 不能静默放行：元数据一坏，陈旧检查恰好失效，比没有检查更危险。
    warn(`${result.reason}，无法判断 pinned 目录的新鲜度，请检查 ${path.basename(pinnedMetaPath)}`)
    return
  }
  const detail = `pinned 模型目录抓取于 ${meta.fetchedAt}（${result.days} 天前，${meta.providers ?? "?"} 个 provider）`
  if (result.days >= STALE_FAIL_DAYS && channel === "prod") {
    // 只拦真正的正式发版；canary/beta/dev 只告警。channel 取自未被 B-pure 改写的
    // dispatch channel，否则 canary 会因 WANLAICODE_CHANNEL 被改写成 prod 而误伤。
    throw new Error(`${detail}，超过 ${STALE_FAIL_DAYS} 天，拒绝用于 prod 发版。${REFRESH_HINT}`)
  }
  if (result.days >= STALE_WARN_DAYS) warn(`${detail}，建议刷新。${REFRESH_HINT}`)
}

async function fromPinned(): Promise<string> {
  const file = Bun.file(pinnedPath)
  if (!(await file.exists())) {
    throw new Error(`无法从 ${modelsUrl} 获取模型目录，且 ${path.relative(dir, pinnedPath)} 不存在。${REFRESH_HINT}`)
  }
  await checkStale()
  const raw = await file.text()
  // 入库文件同样要校验：它比网络响应更容易被人工改坏（手工编辑、合并冲突残留），
  // 而校验缺失时坏数据会被原样写进 models-snapshot.js 并烤进发布产物。
  parseCatalog(raw, path.relative(dir, pinnedPath))
  return raw
}

async function fromNetwork(): Promise<string> {
  // signal 同时覆盖响应头与 body 读取；只给响应头设超时会留下"卡在读 body"的洞。
  const res = await fetch(`${modelsUrl}/api.json`, { signal: AbortSignal.timeout(NETWORK_TIMEOUT_MS) })
  // fetch 对非 2xx 不抛错：代理返回的 403/502 错误页会被当成正文原样写进快照。
  // 实测 models.dev 对不存在的路径还会返回 200 + HTML（SPA fallback），所以状态码
  // 与内容校验两层缺一不可。
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  const raw = await res.text()
  parseCatalog(raw, `${modelsUrl}/api.json`)
  return raw
}

async function resolveCatalog(): Promise<{ data: string; origin: string }> {
  const override = process.env.MODELS_DEV_API_JSON
  if (override) {
    // 这条通道绕过网络与 pinned 兜底，也绕过陈旧检查，因此必须响一声：v0.1.5 发版期间
    // 曾往各 runner 的 .env 注入它指向一份静态快照，忘了撤就会永久静默使用冻结数据。
    warn(
      `正在用 MODELS_DEV_API_JSON=${override} 覆盖模型目录，已跳过新鲜度检查。` +
        `若这是发版临时补丁的残留配置，请清理。`,
    )
    const raw = await Bun.file(override).text()
    parseCatalog(raw, `env:MODELS_DEV_API_JSON(${override})`)
    return { data: raw, origin: "env:MODELS_DEV_API_JSON" }
  }
  try {
    return { data: await fromNetwork(), origin: `${modelsUrl}/api.json` }
  } catch (e) {
    warn(`从 ${modelsUrl} 取目录失败（${(e as Error).message}），改用入库的 pinned 目录`)
    return { data: await fromPinned(), origin: path.relative(dir, pinnedPath) }
  }
}

const catalog = await resolveCatalog()

await Bun.write(
  snapshotPath,
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\n// source: ${catalog.origin}\nexport const snapshot = ${catalog.data}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log(`Generated models-snapshot.js (source: ${catalog.origin})`)
